server:
  port: 8080
#  servlet:
#    context-path: /identity

spring:
  application:
    name: identity-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: doanhndtse161935@fpt.edu.vn
    password: xbmt tevy evrt uouh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: "jdbc:mysql://localhost:3306/hacof"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

outbound:
  identity:
    client-id : ${clientId}
    client-secret : ${clientSecret}
    redirect-uri: "http://localhost:3000/authenticate"

jwt:
  signerKey: "ufTpTQ4N18O8b7+Av2juOo+ekka1oKm0Y022PhDtv1muMGsV23u4UKLNSkJebOc3"
  valid-duration: 3600
  refreshable-duration: 864000

#eureka:
#  client:
#    services-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true