server:
  port: 8080
#  servlet:
#    context-path: /identity

spring:
  application:
    name: identity-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: doanhndtse161935@fpt.edu.vn
    password: xbmt tevy evrt uouh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: "jdbc:mysql://localhost:3306/hacof"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345
#    username: root
#    password: trungkien

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#outbound:
#  identity:
#    client-id: "626901727884-1tjqf1ktfgb32384892hu1dd2360dg0h.apps.googleusercontent.com"
#    client-secret: "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"
#    redirect-uri: "http://localhost:3000/authenticate"


outbound:
  identity:
    client-id: ${clientId}
    client-secret: ${clientSecret}
    redirect-uri: "http://localhost:3000/authenticate"

jwt:
  signerKey: "ufTpTQ4N18O8b7+Av2juOo+ekka1oKm0Y022PhDtv1muMGsV23u4UKLNSkJebOc3"
  valid-duration: 3600
  refreshable-duration: 864000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true