server:
  port: 8080

spring:
  application:
    name: identity-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: doanhndtse161935@fpt.edu.vn
    password: xbmt tevy evrt uouh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: redis
      port: 6379

  datasource:
    url: 'jdbc:mysql://mysql:3306/hacof'
    driverClassName: 'com.mysql.cj.jdbc.Driver'
    username: root
    password: 12345

  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  multipart:
    enabled: true
    max-file-size: 15MB
    max-request-size: 15MB

outbound:
  identity:
    client-id: ${clientId}
    client-secret: ${clientSecret}
    redirect-uri: 'https://hacof.site/authenticate'

jwt:
  signerKey: 'ufTpTQ4N18O8b7+Av2juOo+ekka1oKm0Y022PhDtv1muMGsV23u4UKLNSkJebOc3'
  valid-duration: 3600
  refreshable-duration: 864000

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    bucket-name: ${AWS_S3_BUCKET_NAME}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

logging:
  level:
    com.hacof.identity: debug
