server:
  port: 8081

spring:
  application:
    name: hackathon-service
  datasource:
    url: "jdbc:mysql://localhost:3306/hacof"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: trungkien

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true