server:
  port: 8081

spring:
  application:
    name: hackathon-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: doanhndtse161935@fpt.edu.vn
    password: xbmt tevy evrt uouh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    test-connection: true
  datasource:
    url: "jdbc:mysql://localhost:3306/hacof"
#    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: trungkien

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "ufTpTQ4N18O8b7+Av2juOo+ekka1oKm0Y022PhDtv1muMGsV23u4UKLNSkJebOc3"
  valid-duration: 600000 #3600
  refreshable-duration: 864000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

logging:
  level:
    com.hacof.hackathon.service.impl.EmailServiceImpl: DEBUG
    com.hacof.hackathon.service.impl.NotificationServiceImpl: DEBUG
    org.springframework.mail: DEBUG