server:
  port: 8081
  timezone: Asia/Ho_Chi_Minh

spring:
  application:
    name: hackathon-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    test-connection: true
  datasource:
    url: 'jdbc:mysql://mysql:3306/hacof?serverTimezone=Asia/Ho_Chi_Minh'
    driverClassName: 'com.mysql.cj.jdbc.Driver'
    username: root
    password: 12345
  jackson:
    time-zone: Asia/Ho_Chi_Minh

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: Asia/Ho_Chi_Minh
    show-sql: true

jwt:
  signerKey: 'ufTpTQ4N18O8b7+Av2juOo+ekka1oKm0Y022PhDtv1muMGsV23u4UKLNSkJebOc3'
  valid-duration: 36000
  refreshable-duration: 864000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

logging:
  level:
    com.hacof.hackathon: debug

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    bucket-name: ${AWS_S3_BUCKET_NAME}
