server:
  port: 8081
  servlet:
    context-path: /hackthon

spring:
  application:
    name: hackthon-service
  datasource:
    url: "jdbc:mysql://localhost:3306/hacof"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true