server:
  port: 8082
  servlet:
    context-path: /submission

spring:
  application:
    name: submission-service
  datasource:
    url: "jdbc:mysql://localhost:3306/hacof"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: trungkien

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  multipart:
    enabled: true
    max-file-size: 2MB
    max-request-size: 2MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true