server:
  port: 8083
#  servlet:
#    context-path: /communication

spring:
  application:
    name: communication-service
  datasource:
    url: "jdbc:mysql://localhost:3306/hacof"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans: true
    show-sql: true

jwt:
  signerKey: "ufTpTQ4N18O8b7+Av2juOo+ekka1oKm0Y022PhDtv1muMGsV23u4UKLNSkJebOc3"
  valid-duration: 3600
  refreshable-duration: 864000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true