server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    preferIpAddress: true
logging:
  level:
    '[com.netflix.eureka]': 'OFF'
    '[com.netflix.discovery]': 'OFF'
spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true